### ISSUE TITLE
Something about Point.cs

### ISSUE THREAD

**Issue by VictorZXY** [cotr/PhysicsSimulator#3]
Why are the X and Y of the point double? They should be integers because pixels, which are considered our basic physical quantities, are integers.

**Comment by xfoxfu** [comment]
Due to some reasons, `Speed`, `Force`, `Accelerated_Speed` are all **double**, just because there are more availability for the points and the models. You may convert the value to `int32` and draw the points.
_If no more questions, I'll close the issue.And also, you may comment on the code of `Point.cs` instead of open a new issue._
**Please use MARKDOWN to write things.**
